# Generated by Django 3.0.8 on 2020-07-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentlocation', '0002_auto_20200709_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='personellocation',
            name='address',
            field=models.CharField(default='foorbar', max_length=200),
        ),
    ]
