# Generated by Django 3.0.8 on 2020-07-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentlocation', '0003_personellocation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personellocation',
            name='location',
        ),
    ]
